<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="10190" started-at="2018-09-25T02:41:15Z" finished-at="2018-09-25T02:41:25Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="10166" started-at="2018-09-25T02:41:15Z" finished-at="2018-09-25T02:41:25Z">
      <class name="stepDefinitions.Verify_Login_Page">
        <test-method status="PASS" signature="user_launches_adactin_page()[pri:0, instance:stepDefinitions.Verify_Login_Page@271053e1]" name="user_launches_adactin_page" duration-ms="9849" started-at="2018-09-25T08:11:15Z" finished-at="2018-09-25T08:11:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_launches_adactin_page -->
        <test-method status="FAIL" signature="user_enters_and(java.lang.String, java.lang.String)[pri:0, instance:stepDefinitions.Verify_Login_Page@271053e1]" name="user_enters_and" duration-ms="0" started-at="2018-09-25T08:11:25Z" finished-at="2018-09-25T08:11:25Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method user_enters_and requires 2 parameters but 0 were supplied in the @Test annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method user_enters_and requires 2 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:198)
	at org.testng.internal.Parameters.createParameters(Parameters.java:134)
	at org.testng.internal.Parameters.createParameters(Parameters.java:370)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:447)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1389)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1081)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1186)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_enters_and -->
        <test-method status="FAIL" signature="user_clicks_login_button()[pri:0, instance:stepDefinitions.Verify_Login_Page@271053e1]" name="user_clicks_login_button" duration-ms="268" started-at="2018-09-25T08:11:25Z" finished-at="2018-09-25T08:11:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<http://www.adactin.com/HotelApp/SearchHotel.php> but was:<http://www.adactin.com/HotelApp/>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<http://www.adactin.com/HotelApp/SearchHotel.php> but was:<http://www.adactin.com/HotelApp/>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at stepDefinitions.Verify_Login_Page.user_clicks_login_button(Verify_Login_Page.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_clicks_login_button -->
      </class> <!-- stepDefinitions.Verify_Login_Page -->
    </test> <!-- Test -->
    <test name="Test1" duration-ms="10190" started-at="2018-09-25T02:41:15Z" finished-at="2018-09-25T02:41:25Z">
      <class name="stepDefinitions.Verify_Login_Page">
        <test-method status="PASS" signature="user_launches_adactin_page()[pri:0, instance:stepDefinitions.Verify_Login_Page@55d56113]" name="user_launches_adactin_page" duration-ms="9879" started-at="2018-09-25T08:11:15Z" finished-at="2018-09-25T08:11:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_launches_adactin_page -->
        <test-method status="FAIL" signature="user_enters_and(java.lang.String, java.lang.String)[pri:0, instance:stepDefinitions.Verify_Login_Page@55d56113]" name="user_enters_and" duration-ms="0" started-at="2018-09-25T08:11:25Z" finished-at="2018-09-25T08:11:25Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method user_enters_and requires 2 parameters but 0 were supplied in the @Test annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method user_enters_and requires 2 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:198)
	at org.testng.internal.Parameters.createParameters(Parameters.java:134)
	at org.testng.internal.Parameters.createParameters(Parameters.java:370)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:447)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1389)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1081)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1186)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_enters_and -->
        <test-method status="FAIL" signature="user_clicks_login_button()[pri:0, instance:stepDefinitions.Verify_Login_Page@55d56113]" name="user_clicks_login_button" duration-ms="279" started-at="2018-09-25T08:11:25Z" finished-at="2018-09-25T08:11:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<http://www.adactin.com/HotelApp/SearchHotel.php> but was:<http://www.adactin.com/HotelApp/>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<http://www.adactin.com/HotelApp/SearchHotel.php> but was:<http://www.adactin.com/HotelApp/>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at stepDefinitions.Verify_Login_Page.user_clicks_login_button(Verify_Login_Page.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_clicks_login_button -->
      </class> <!-- stepDefinitions.Verify_Login_Page -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
